# Site settings
title: "Kesegotumisang • Resume"
description: "My resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kesego Tumisang"
resume_title:                   "Lead Developer(Mobile)"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kesego.tumisang@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+267 72 642 364"
resume_contact_address:         "P O Box 472, Letlhakeng, Botswana"

resume_header_contact_info:     "P O Box 472, Letlhakeng, Botswana • +267 72 642 364 • kesego.tumisang@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>An aspiring techpreneur and has been quite active in the tech space,</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kesegotumisang"
  resume_twitter_url:           "http://twitter.com/kesegotumisang"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://fb.com/kesego.tumisang"
  resume_linkedin_url:          "https://www.linkedin.com/in/kesegotumisang"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://kesegotumisang.com"
  resume_medium_url:            "https://medium.com/@kesegotumisang"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
